### ISSUE TITLE
Show player's health

### ISSUE THREAD

**Issue by SodyM** [SodyM/SpaceShip#8]
Show player's healt in top infoline just like it in Seachase is.

**Comment by eqoh2** [comment]
Proposal
- I will add a Health property to the AnimatedUIObject class so that both player and enemies have that property.

**Comment by SodyM** [comment]
Sounds good. Go for it, I'll take a care about that healthbar of player.

UI proposal for next step:
What about some kind of this:
Health 100% - Heino is OK
Health 50% - Heino will be scared
Health 10% - Heino will be angry or totaly down

Something like this http://doom.wikia.com/wiki/Status_bar_face.
Check that table and http://vignette1.wikia.nocookie.net/doom/images/c/c8/Doomfacepsxjibdead.gif/revision/latest?cb=20120222100323 for more details
